lib/utils/merge-configs.util.ts, package-lock.json, package.json, tests/e2e/load-nested-files.spec.ts, tests/src/app.module.ts, tests/src/nested-database.config.ts
```
[x] Bugfix
[ ] Feature
```
This failed:
```ts
export default registerAs('database.mongo', () => ({
host: 'host',
port: 4000,
}));
// and then...
this.configService.get('database.mongo.host'); // returns undefined
```
This doesn't fail & works as intended
```ts
export default registerAs('database.mongo', () => ({
host: 'host',
port: 4000,
}));
// and then...
this.configService.get('database.mongo.host'); // returns 'host'
```
```
[ ] Yes
[x] No
```
It was only fair to use lodash …
=> Bugfix: Loaded config token names (dot separated)

lib/config.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
When provided a `defaultValue`, `ConfigService.get` still returns `T | undefined`, which leads to unnecessary error in strict mode of Typescript.
When provided a `defaultValue`, `ConfigService.get`returns `T`.
When `defaultValue` is not provided, `ConfigService.get`returns `T | undefined`, as before.
```
[ ] Yes
[x] No
```
=> Add a overload to ConfigService.get so that it will not returns undefined when defaultValue is provided

lib/config.module.ts, lib/interfaces/config-module-options.interface.ts, package-lock.json, package.json, tests/e2e/load-env-expanded.spec.ts, tests/src/.env.expanded, tests/src/app.module.ts
```
[ ] Bugfix
[x] Feature
```
No way to expand variables.
Issue Number: #25 
Added `expandVariables` as an option to expand the follow `.env` for eg.
```
URL=myapp.test
EMAIL=support@${URL}
```
Now, `EMAIL=support@myapp.test` if `options.expandVariables=true`
```
[ ] Yes
[x] No
```
I'll update the [nestjs/docs.nestjs.com](https://github.com/nestjs/docs.nestjs.com) when this PR is merged 😄
=> Added dotenv-expand, updated modules & updated tests

package.json
The @types/dotenv package has been deprecated.
See https://github.com/motdotla/dotenv/pull/430 and https://github.com/motdotla/dotenv/releases/tag/v8.2.0
=> Remove @types/dotenv dev dependency

lib/config.service.ts, lib/types/index.ts, lib/types/no-infer.type.ts
```
[x] Bugfix
[ ] Feature
```
When calling `ConfigService.get(propertyPath, defaultValue)`, TypeScript will incorrectly infered the type of `defaultValue` as the return type if the generic was omitted.
```typescript
const value: string = this.configService.get('database.host', 'localhost');
```
Will be infered as:
```typescript
const value: string = this.configService.get<'localhost'>('database.host', 'localhost');
```
```typescript
const value: string = …
```
=> fix: fixes the infer bug of `ConfigService.get`

lib/config.module.ts, tests/e2e/load-priority.spec.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: 168
Values returned from `ConfigService` should prioritize environment variables over dotenv files when using schemaValidation like it does when not using schemaValidation.
```
[ ] Yes
[X] No
```
=> fix: consistent config values with schema validation

lib/config.service.ts, tests/e2e/optional-generic.spec.ts
```
[ ] Bugfix
[x] Feature
```
`ConfigService` will accept any string for the property path
Can pass in an optional generic to `ConfigService` to validate the env variables being accessed.
If you have the following interface that matches the expected env variables
```
export interface EnvVariables {
PORT: string;
TIMEOUT: number;
}
```
Then when injecting `ConfigService` into a constructor the property pass will be validated again the keys of the generic type.
```
@Injectable()
class SomeService { …
```
=> feat(config): add optional generic type to config service

lib/config.module.ts, lib/interfaces/config-module-options.interface.ts, tests/e2e/validate-function.spec.ts, tests/src/app.module.ts
```
[ ] Bugfix
[x] Feature
```
Only `joi` validation is possible, which is forcing users to add this lib in addition to `class-validator`  
Issue Number: [318](https://github.com/nestjs/config/issues/318)
A user can now choose between `class-validator` and `joi` to validate env variables
```
[ ] Yes
[x] No
```
=> feat(core): add possibility to use a custom validate function for env validation

lib/utils/index.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Issue Number: #467 
N/A
```
[ ] Yes
[x] No
```
This PR, added export for  method get config token
=> chore(utils): added export for  method get config token 

lib/utils/create-config-factory.util.ts
`uuidv4()` is being called even if it's not used.
Inlines the `uuid()` call to rely on JS short circuit on OR operation to generate the uuid v4 only if the factory key was not provided. The `factory.KEY` will always be defined for those that are using `registerAs`, thus they can avoid the computation of `uuidv4()`
```
$ node
> const foo = () => {}
> const bar = () => console.log('called')
> false || foo( bar() )
called
undefined
> true || foo( bar() )
true
```
=> refactor(utils): generate unique id only when needed

lib/types/path-value.type.ts
Issue Number: fixes #906
we can have keys with the type `any` when using `ConfigService#get` typed. See:
The second commit is just a minor performance improvement **not related** with the original Issue. It was made to avoid computing `PathImpl2<T>` twice by using the [`infer`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#type-inference-in-conditional-types) keyword to cache the first result.  
I can drop that commit if you prefer the old version in favor of readability.
=> fix(types): stop before try to evaluate `any` as a path

lib/config.service.ts
Users must either use full schema validation of configuration values or write their own `.getOrThrow()` method.
`ConfigService#getOrThrow()` can be used to get a configuration value by key, and throw if it does not exist (and no default value was provided).
[Relevant Discord conversation](https://discord.com/channels/520622812742811698/939229065527820369/971538667195744317).
=> feat: add ConfigService#getOrThrow()

lib/config.service.ts, tests/e2e/optional-generic.spec.ts
Currently `getOrThrow` return type is whole config object instead of `propertyPath` type.
`getOrThrow` return type is same as `K[propertyPath]`
=> fix(common): infer getOrThrow return value

lib/config.service.ts
The return type of a validated `ConfigService.get` excludes `undefined`. This hides null errors in the following case.
```typescript
class Env {
OPT?: string
}
const configService = app.get<ConfigService<Env, true>>(ConfigService);
const opt = configService.get('OPT', {infer: true}) // type is: string, should be string | undefined
const hasCat = opt.includes('🐱') // Will result in runtime error because opt is undefined
``` 
Issue Number: #1302
The return type now no longer excludes undefined if `WasValidated` is true.
Users that have _strictNullChecks_ enabled, have optional properties on their Env class, and depend on the behavior of `ConfigService.get` stripping `undefined` from the …
=> fix(): do not remove undefined from ConfigService.get return type

lib/config.module.ts, tests/e2e/optional.spec.ts
- Environment variables are assigned back to `process.env` resulting in unexpected stringification. This stringification is deprecated and might result in a runtime error in the future. See <https://nodejs.org/api/process.html#processenv>.
- The return value for an undefined variable from `ConfigService.get` is the string `'undefined'`.
Issue Number: Closes #1302, address part 1.
- Only strings are assigned back to `process.env`
- Undefined variables result in `undefined` as return type from `ConfigService.get`
=> fix(): prevent unexpected process env stringification

lib/config.service.ts, lib/utils/merge-configs.util.ts
this is the recommended way to load only the methods needed instead of entire lodash.
lodash is imported entirely in to the package. when most of it not needed at all.
it makes 78.3% of the bundle!
imports only the relevant methods. This is the recommended way to pick methods from lodash.
This improves pull request 792, which moved to using the full lodash package,
but made inefficient imports.
pull request improved: https://github.com/nestjs/config/pull/792/
article about importing lodash: https://www.labnol.org/code/import-lodash-211117
=> pref():import lodash efficiently

lib/conditional.module.ts, lib/index.ts, tests/e2e/.env.conditional, tests/e2e/conditional.module.spec.ts
There's no utility method for conditionally registering modules
Issue Number: #1407
With the new `ConditionalModule` devs can now register modules based on keys in the `process.env` or have them registered as blanks modules under the guise of a dynamic module. This works for nested modules, multiple imports, and dynamic modules.
=> feat: create a conditional module

lib/config-host.module.ts, lib/config.module.ts, lib/config.service.ts, lib/interfaces/config-module-options.interface.ts, lib/types/config-object.type.ts, lib/types/config.type.ts, lib/utils/create-config-factory.util.ts, lib/utils/get-config-token.util.ts, lib/utils/get-registration-token.util.ts, lib/utils/merge-configs.util.ts, lib/utils/register-as.util.ts
Proposal:
Annotate user-facing APIs with `@publicApi`, since in the recently added `"ConditionalModule"` module the `@publicApi` annotation was added(see here: https://github.com/nestjs/config/blob/master/lib/conditional.module.ts#L5), it would be nice if all user-facing APIs in this package had the api public annotation.
If there are private APIs that are not public, which I forgot, please let me know so I can update the PR.
=> chore(): marked apis public

lib/config.module.ts, lib/config.service.ts, tests/e2e/update-env.spec.ts
Currently we can get environment variables and set cache. But there's no feature for setting environment variables dynamically. This could be useful even when testing the server locally so to make it dynamically updated when reloaded.
Issue Number: #1476 
This PR adds feature for setting/updating environment variables with the method `set` in `ConfigService`. And as `@nestjs/config` depends of `dotenv-expand` to resolve interpolation, I could get hint from **NOT being interpolated**. 
So after getting environment paths from module's config, simply can parse the environment variables as raw strings (I mean, like the option `expandVariables` to `false`). And then simply just replacing …
=> feat: set or update environment variables dynamically (#1476)

tests/e2e/cache.spec.ts, tests/e2e/load-priority.spec.ts
I made a similar test file in config repo simply.
```
describe('Test Case', () => {
let envBackup;
beforeAll(() => {
envBackup = process.env;
});
describe('Test Case 1', () => {
it('run test 1', () => {
process.env['a'] = "8000";
expect(process.env.a).toBe("8000");
});
});
describe('Test Case 2', () => {
it('run test 2', () => {
expect(process.env.a).toBe("8000");
});
});
afterEach(() => {
process.env = envBackup;
});
});
```
In this case we expect `run test 2` to be failed. We guess the process.env will be reset in afterEach.
but it succeed.
Because `envBackup` variable is reference of `process.env`. If you change either `envBackup` or `process.env`, both of them …
=> test(@nestjs/config) reset env correctly

lib/conditional.module.ts
When conditional module was used in integration
tests with jest, then an open handle would be
reported due to setTimeout promise not triggering
before the tests execution finishes.
To avoid open handles close the timeout instead of setting a boolean variable and checking its value
after 5 (by default) seconds.
Timeout is set when `ConditionalModule.registerWhen` is executed, but it is never stopped. Instead a boolean variable is used to avoid throwing an error when it is not necessary. This timeout is not always triggered during tests execution which leads to a problem with an open handle.
Nothing changes in terms of method execution, but instead of using a boolean …
=> fix: close timeout in ConditionalModule

tests/e2e/load-priority.spec.ts, tests/src/app.module.ts
I have a curiosity to see how config module works.
I think nestjs documents don't provide enough explanations.
If both .env file and load configration are provided, load configuration override .env vars?
If multiple load configrations are provided, last configuration take precedence?
That's why I add a couple of tests.
These tests answer following questions.
both .env file and load configuration, what's the priority?
multiple load configurations, what's the priority?
=> test(@nestjs/config) add more tests for priority

lib/conditional.module.ts
Add an option `debug` defaulted to true to the `registerWhen` method and only create debug log when it is set to true. Also adjust the type for options.timeout to be optional.
Currently a ConditionalModule is run when a javascript module is loaded but before any NestJS setup occurs.  The ConditionalModule.  In this case, the module will output a debug log via the default ConsoleLogger with no ability to silence the message.
Add an option to the ConditionalModule's registerWhen method to disable the debug message.
The debug flag is defaulted to true so that no change will be observed, however the timeout option is being flagged as optional so previous code that would …
=> feat: ability to disable debug message in ConditionalModule

lib/config.service.ts
This change extends the KeyOf type to support symbol keys when keyof T extends never. This allows the config service to properly handle configurations that use symbols as keys.
TypeScript error when using symbol as key in `ConfigService.get()` or `ConfigService.getOrThrow()`  inside main.ts
```
Argument of type 'SYMBOL_KEY' is not assignable to parameter of type 'string'.
```
Issue Number: #1996
Symbol keys work directly without casting, providing proper type safety.
None...
=> fix(common): update KeyOf type to support symbol keys
